#!/bin/bash


#SBATCH --job-name=ASSEMBLE_F4
#SBATCH -o %A_%a.ASSF.out
#SBATCH -e %A_%a.ASSF.err
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=Chasemaughan@gmail.com  #change email to personal/work
#SBATCH --mem-per-cpu=6gb
#SBATCH --time=48:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=16
#SBATCH --array=1-96 # doesn't need to change, but based off of number of names in "ephem_names_new.txt"


# -b to line12 for burst
source ~/.bashrc
module purge
module load miniconda3
source activate chase  #enviroment needs to be changed to match downloaded one
export PATH=$PATH:`pwd`


#Set tmp dir on node it is running on for spadesoutput and make the tmp dir as unix sort used in python script  need the dir made or will fail

TMPDIR=/tmp/$SLURM_JOB_ID\_$SLURM_ARRAY_TASK_ID
mkdir $TMPDIR

#parses slist for array should be tab delimited each line should have  taxaname read1 read2
taxa=$(head -n $SLURM_ARRAY_TASK_ID ephem_names_new.txt | tail -n1|cut -f3)
INFILE1=$(head -n $SLURM_ARRAY_TASK_ID ephem_names_new.txt | tail -n1|cut -f1)
INFILE2=$(head -n $SLURM_ARRAY_TASK_ID ephem_names_new.txt | tail -n1|cut -f2)

python ASS_F4_fast.py -ing tanypteryx.fasta -inp R1_tanypteryx1306_R.fasta -inpc TESTprobehits_out -threads 16 -tname $taxa -flanksize 2 -1 $INFILE1 -2 $INFILE2  -rname tanypteryx
